# This file generates the GitHub Actions matrix
---
include:
  # melior
  # - board: nice_nano
  #   shield: melior_central_dongle dongle_display
  #   artifact-name: home_melior_central_dongle
  #   #cmake-args: -DCONFIG_ZMK_STUDIO=y
  #   #snippet: studio-rpc-usb-uart
  # - board: xiao_ble
  #   shield: melior_central_left
  #   artifact-name: home_melior_central_left
  #   #cmake-args: -DCONFIG_ZMK_STUDIO=y
  #   #snippet: studio-rpc-usb-uart
  - board: xiao_ble//zmk
    shield: melior_peripheral_left
    artifact-name: melior_peripheral_left
  - board: xiao_ble//zmk
    shield: melior_peripheral_right
    artifact-name: melior_peripheral_right
  - board: nice_nano//zmk
    shield: melior_central_snake snake_adapter
    artifact-name: melior_snake_dongle
    #cmake-args: -DCONFIG_ZMK_STUDIO=y
    #snippet: studio-rpc-usb-uart
  # - board: xiao_ble//zmk
  #   shield: melior_central_prospector prospector_adapter
  #   artifact-name: melior_prospector_dongle
    #cmake-args: -DCONFIG_ZMK_STUDIO=y
    #snippet: studio-rpc-usb-uart
  # reset
  - board: nice_nano
    shield: settings_reset
  - board: xiao_ble
    shield: settings_reset
